name: MakeCode

on: 
  release:
    types:
      - created
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: |
          npm install -g pxt
          pxt target arcade
      - name: build samd51
        run: |
          pxt clean
          pxt install --hw samd51
          pxt build --hw samd51 --cloud
      - name: upload samd51
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://github.com/${{ github.repository }}/releases/${{ github.event.release.id }}/assets 
          asset_path: ./built/binary.uf2
          asset_name: samd51.uf2
          asset_content_type: application/octet-stream
      - name: build stm32f401
        run: |
          pxt clean
          pxt install --hw stm32f401
          pxt build --hw stm32f401 --cloud
      - name: build rpi
        run: |
          pxt clean
          pxt install --hw rpi
          pxt build --hw rpi --cloud
